export const LAMBDA_URL = "https://m8o1q7cin4.execute-api.us-east-2.amazonaws.com/prod";
export const FALLBACK_MESSAGES = [
  "Not getting divorced sooner. Spent too much time being miserable.",
  "Not spending enough time with my son when he was younger.",
  "Spending too much time on side projects at the expense of spending time with my kids.",
  "Not pursuing mathematics when I was doing my cs degree in college.",
  "I smoked wayyyy too much weed in high school and college. I experience brain fog all too often now. I can't remember what it feels like to think clearly to be honest",
  "Holding back in life",
  "Not marrying my high school sweetheart.",
  "Having children. Decided it wasn't for me.",
  "Spending way too much time at work instead of investing it in myself.",
  "Not buying a thousand bitcoins when they were worth $3!",
  "Getting married to the wrong person. Now Im close to 40, no kids, mostly bald. No one wants to take a chance on me. I just spent a weekend hanging out with friends who have 6-10 year olds and I really think I've missed out. I wasted my time and her time. Time is the one thing you cant get back. Don't waste it on the wrong person. Getting married to the wrong person. Now Im close to 40, no kids, mostly bald. No one wants to take a chance on me. I just spent a weekend hanging out with friends who have 6-10 year olds and I really think I've missed out. I wasted my time and her time. Time is the one thing you cant get back. Don't waste it on the wrong person.",
  "Not taking excellent care of my teeth. I've spent enough for 2 new cars over the years in root canals, crowns and implants, not to mention all the pain and discomfort prior to affording all of the work.\n\nBrush your teeth. Often. Even though it sucks, you should also Floss. Every day. Go to your semi-annual cleanings. This can all be avoided very easily.",
  "drinking too much. letting the weight back on after losing it. being afraid of sex. complaining about visiting my grandparents, If they were here today I would immediately tell them how much they meant to me",
  "Moving from America to a 3rd world country when I was 14. It was my parents' decision, not mine, but it changed me for the worse. It was the biggest turning point in my life and will always be my biggest regret.",
  "I wish I would of spent more time with my Grandpa and Grandma.",
  "Deciding not to go to dental school because of the cost. Now I'm stuck in a lab 5 days a week, sometimes longer whereas my friends work 3-4 days a week and can dictate their own days off.",
  "Not learning to get over my shyness when I was younger. Would have had a lot more fun.",
  "College was basically pointless. I guess I'm glad I didn't drop out of HS, but I had job offers from some big .com names when I was a teen in the 90s.\n\nI really wish I had not gone to college.",
  "poly sci major in college. I now work in IT. I always had a knack for pcs as I was a big pc gamer. I didn't want to be stuck in front of computers all day. went to study a liberal arts. 10 years later and I been mostly stuck in front of computers. Switched career over to IT and now I make as much as a comp science graduate would make out of college 80k. I feel like i wasted 8 years. I could be making at least 130k if i had studied IT and started earlier.",
  "My biggest regret is not going to nursing school.I am 53 now and wish I would have pursued it.I worked at a hospital for 15 years as a tech and could have went and had some of it paid for through my job.",
  "Not getting married and having children. My dad is dying and it sucks to know that I won't have someone that gives a shit about me when my time comes.",
  "Being born. No real friends ever. Plenty of bullies. Kicked by people from age 10 to 59 - my current age. There is nothing I look back on and say \"that was worth all of the suffering\". No good memories. None.",
  "At 23, my biggest regret is having hooked up with a guy I'd known for an hour.\n\nOr, no. Having lost my virginity to a guy I'd known for an hour.\n\nI met him my first day of college, then went back to his place after class, and made the biggest mistake of my life.",
  "Giving up",
  "Watching my first marriage fail. That still fucks with me years later.",
  "I regret going to college. I have a masters degree and $130,000 in debt. It has been about 8 years since I graduated and I'm working in a job that barely requires a high school diploma.",
  "I have a few... but the biggest is that I never finished college. I know I can go back but the road thus far has been rather difficult.",
  "Can't say.",
  "None",
  "Everything",
  "I HAVE NO REGRETS.",
  "I have no regrets",
  "I don't live with regrets.",
  "To be, or not to be, that is the question",
  "Not getting treated for depression earlier.",
  "Not having children. It would have been fun watching them grow up and helping them through this journey we call life.",
  "When my dad got admitted to the hospital, I should have called to talk to him. I should have flown back to my country to see him. But I didn't. I waited until new years day to call him just to find out he was gone. On new year's day.",
  "Worrying about the future so much, and trying to over plan everything. I've realized a lot of unhappiness stems from constantly wanting and looking into the future at what's coming next. May as well just enjoy what's going on around you.",
  "I don't have a relationship with any family member outside of my immediate family.",
  "Hacker News",
  "Pursuing a start up.",
  "Letting her go",
  "Dropping out of college. It basically ruined my whole life, and I have no way of getting back on track at the moment. 2 months from turning 30 as well....",
  "Too many missed opportunities",
  "Being a heroin addict",
  "Taking that first hit.",
  "My father is much older than I am. 42 years older to be exact. When I was a teenager I was a really asshole to him and didn't treat him right or help enough. I've tried to make up for it over the past 10 years but now that his health is declining, 74 years old, I've really felt shitty about how I treated him.",
  "Hanging out with a friend instead of visiting my father in the hospital. He died that night and I never got to say goodbye.",
  "Selling all my bitcoins when they hit $10",
  "My biggest regret saying yes to a marriage proposal when I was 23 that caused me to waste a good part of my 20s engaged to someone who I knew wasn't a good match in the first place. I did this heavily because of family and outside pressure.",
  "Not coming out before college. It was my first chance to actually be me and I fucked it up. I've essentially caged myself and can't come out now; I'm in ROTC and would end up getting kicked out, which I know would just piss my parents off and end up with me having no way to pay for college.",
  "Stopped taking my antidepressants because I was feeling better. Turned into a monster and ruined my relationship.\nDefinitely learned my lesson. One year later and I take my pills everyday. Just wish it didn’t cost me my partner."
];

export function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
