export function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
};
export const LAMBDA_URL = "https://m8o1q7cin4.execute-api.us-east-2.amazonaws.com/prod";
export const FALLBACK_MESSAGES = [
  "I regret playing the trombone for 8 years instead of learning piano or guitar.",
  "I should have stuck with those piano lessons. Mom you were right!!",
  "I regret not learning how to program when I was younger. I wonder how much better I'd be by now...",
  "I regret not hugging my mom enough. You never know what you have until it's gone...",
  "I invested too much into work at the expense of family, friends, and my own happiness. And I really don't have much to show for it.",
  "Spending too much time on the computer. No social life. 30 year old virgin.",
  "Having sex before marriage.",
  "cocaine is one hell of a drug",
  "I regret staying in a loveless marriage for too long.",
  "Being married to the wrong woman. Having kids. Picking the wrong career.",
  "I regret not investing my money in the stock market and letting it sit in my savings account. COMPOUND INTEREST .",
  "I regret not exercising in my 20s. I'm a fat piece of shit who doesn't contribute to society. I wish I could do a pull up",
  "I regret being too afraid to dance when I was younger. I regret not dancing now",
  "I regret being too afraid to ask out that girl I always wanted to date.",
  "My life.",
  "Getting married to the wrong person. Now Im close to 40, no kids, mostly bald. No one wants to take a chance on me. I just spent a weekend hanging out with friends who have 6-10 year olds and I really think I've missed out. I wasted my time and her time. Time is the one thing you cant get back. Don't waste it on the wrong person.",
  "Not going out, not meeting girls. No matter how spoiled I know they are (at least where I come from), I'd still be getting some. Probably it's because I had confidence issues, or maybe it's because I don't drink. Now, I ended up with a long distance girlfriend who i'm still to meet, who I have an opinion doesn't try so hard to meet me, while I'm desperate on finding a job.",
  "Not working out when I was a teenager. I would have put on muscle so much faster than I am now.",
  "Not taking excellent care of my teeth. I've spent enough for 2 new cars over the years in root canals, crowns and implants, not to mention all the pain and discomfort prior to affording all of the work. Brush your teeth. Often. Even though it sucks, you should also Floss. Every day. Go to your semi-annual cleanings. This can all be avoided very easily.",
  "The day my dad killed himself, I was walking out of the house and running late for class. He asked me to have some breakfast with him but I said no and walked out.",
  "I regret not networking more in college. Turns out who you know is more important than what you know.",
  "I stayed in a shitty relationships because of guilt and fear. I should have stayed in because I liked it, but I wasted a lot of time with this woman.",
  "I fucked up my marriage by cheating on my spouse. Don't ever do it if you have the opportunity. Don't even THINK about doing it.",
  "Not making more friends. Not getting laid.",
  "Not spending more time with my parents - walking, talking, travelling - while they were still young enough to actively enjoy it.",
  "I regret the coffee I just spilled on myself 🤦‍♂️",
  "I regret being so lazy for much of my life. So much wasted potential there..",
  "I regret being ugly. I feel like I'm completely invisible. All of my attempts at romance are rejected, and while looks are never the stated reason, I do know it's a big component. I wonder what human experiences I've missed because I'm so deformed.",
  "I regret quitting my job to travel right before COVID happened. Now I have no income and no experiences to show for it. Also cooped inside all day with my parents.",
  "I'm stuck in a job and an industry only because of the money. I honestly don't know what alternative career path I can take, and I'm not sure I am willing to give up the comforts of my job. Golden handcuffs, as they say.",
  "Reading all of these regrets, I regret not hugging my wife this morning before she left for work.",
  "I regret moving back in with my parents after college. I'm 24, still young, but I'm closer to my thirties than I am to my twenties. Thinking about the number of opportunities I've missed in life physically hurts...",
  "Marrying too early. Have fun in your 20s kids, instead of having them",
  "I regret not making more friends in college. I focused too much on my studies and computers. In hindsight, it was the perfect time to reinvent my life. Fuck it, I KNEW IT AT THE TIME. I don't know when this feeling of resentment will go away.",
  "I just read that someone regrets not exercising in their 20s. Well guess what - I regret not exercising in my thirties :)",
  "The best time to plant a tree was ten years ago. The second best time is now.",
  "I regret programming. As a programmer I'm just average or below average. I only did it because I liked math but wanted to pursue something practical and maybe lucrative. I would love to do a PhD but dread the grind of academia.",
  "I regret everything about my life journey so far. I wish I could change all of it.",
  "I regret cheating on my wife. She's the best thing that I've had happen to me.. i'm afraid what will happen if she finds out.",
  "Not getting divorced sooner. Spent too much time being miserable.",
  "Not spending enough time with my son when he was younger.",
  "Spending too much time on side projects at the expense of spending time with my kids.",
  "Not pursuing mathematics when I was doing my cs degree in college.",
  "I smoked wayyyy too much weed in high school and college. I experience brain fog all too often now. I can't remember what it feels like to think clearly to be honest",
  "Holding back in life",
  "Not marrying my high school sweetheart.",
  "Having children. Decided it wasn't for me.",
  "Spending way too much time at work instead of investing it in myself.",
  "Not buying a thousand bitcoins when they were worth $3!",
  "drinking too much. letting the weight back on after losing it. being afraid of sex. complaining about visiting my grandparents, If they were here today I would immediately tell them how much they meant to me",
  "Moving from America to a 3rd world country when I was 14. It was my parents' decision, not mine, but it changed me for the worse. It was the biggest turning point in my life and will always be my biggest regret.",
  "I wish I would of spent more time with my Grandpa and Grandma.",
  "Deciding not to go to dental school because of the cost. Now I'm stuck in a lab 5 days a week, sometimes longer whereas my friends work 3-4 days a week and can dictate their own days off.",
  "Not learning to get over my shyness when I was younger. Would have had a lot more fun.",
  "College was basically pointless. I guess I'm glad I didn't drop out of HS, but I had job offers from some big .com names when I was a teen in the 90s.\n\nI really wish I had not gone to college.",
  "poly sci major in college. I now work in IT. I always had a knack for pcs as I was a big pc gamer. I didn't want to be stuck in front of computers all day. went to study a liberal arts. 10 years later and I been mostly stuck in front of computers. Switched career over to IT and now I make as much as a comp science graduate would make out of college 80k. I feel like i wasted 8 years. I could be making at least 130k if i had studied IT and started earlier.",
  "My biggest regret is not going to nursing school.I am 53 now and wish I would have pursued it.I worked at a hospital for 15 years as a tech and could have went and had some of it paid for through my job.",
  "Not getting married and having children. My dad is dying and it sucks to know that I won't have someone that gives a shit about me when my time comes.",
  "Being born. No real friends ever. Plenty of bullies. Kicked by people from age 10 to 59 - my current age. There is nothing I look back on and say \"that was worth all of the suffering\". No good memories. None.",
  "At 23, my biggest regret is having hooked up with a guy I'd known for an hour.\n\nOr, no. Having lost my virginity to a guy I'd known for an hour.\n\nI met him my first day of college, then went back to his place after class, and made the biggest mistake of my life.",
  "Giving up",
  "Watching my first marriage fail. That still fucks with me years later.",
  "I regret going to college. I have a masters degree and $130,000 in debt. It has been about 8 years since I graduated and I'm working in a job that barely requires a high school diploma.",
  "I have a few... but the biggest is that I never finished college. I know I can go back but the road thus far has been rather difficult.",
  "Everything",
  "I HAVE NO REGRETS.",
  "I have no regrets",
  "I don't live with regrets.",
  "To be, or not to be, that is the question",
  "Not getting treated for depression earlier.",
  "Not having children. It would have been fun watching them grow up and helping them through this journey we call life.",
  "When my dad got admitted to the hospital, I should have called to talk to him. I should have flown back to my country to see him. But I didn't. I waited until new years day to call him just to find out he was gone. On new year's day.",
  "Worrying about the future so much, and trying to over plan everything. I've realized a lot of unhappiness stems from constantly wanting and looking into the future at what's coming next. May as well just enjoy what's going on around you.",
  "I don't have a relationship with any family member outside of my immediate family.",
  "Pursuing a start up with my own money.",
  "Letting her go",
  "Dropping out of college. It basically ruined my whole life, and I have no way of getting back on track at the moment. 2 months from turning 30 as well....",
  "Too many missed opportunities",
  "Being a heroin addict",
  "Taking that first hit.",
  "My father is much older than I am. 42 years older to be exact. When I was a teenager I was a really asshole to him and didn't treat him right or help enough. I've tried to make up for it over the past 10 years but now that his health is declining, 74 years old, I've really felt shitty about how I treated him.",
  "Hanging out with a friend instead of visiting my father in the hospital. He died that night and I never got to say goodbye.",
  "Selling all my bitcoins when they hit $10",
  "My biggest regret saying yes to a marriage proposal when I was 23 that caused me to waste a good part of my 20s engaged to someone who I knew wasn't a good match in the first place. I did this heavily because of family and outside pressure.",
  "Not coming out before college. It was my first chance to actually be me and I fucked it up. I've essentially caged myself and can't come out now; I'm in ROTC and would end up getting kicked out, which I know would just piss my parents off and end up with me having no way to pay for college.",
  "Stopped taking my antidepressants because I was feeling better. Turned into a monster and ruined my relationship.\nDefinitely learned my lesson. One year later and I take my pills everyday. Just wish it didn’t cost me my partner.",
  "not pulling out",
  "Letting my fiance travel to Europe. he cheated on me. BUt maybe that would have happened anyways.",
  "Worrying what other people thought of me. Still worrying about what people think about me",
  "Being depressed for most of my teens and current age",
  "working too much at the expense of my own growth and development",
  "trying to advance my career at the cost of my own health and family",
  "Marrying the person I thought I knew",
  "Not appreciating my parents while they were still around.",
  "Not being able to pay for my dogs surgery",
  "Not leaving my first job quick enough. Got too complacent with life and now I'm further behind than I would like",
  "Not investing in AAPL in 2011",
  "i want a restart button for my own life",
  "I wasted a decade playing video games. If only I could have leveled up my IRL character",
  "I regret attending Princeton. The atmosphere was super competitive and cutthroat and didn't make a lot of friends. Was also depressed the whole time",
  "Watching time slip away day by day.",
  "Being a depressed, abusive, alcoholic.",
  "Spending my income buying guitars when I couldn't pay for a mortgage at the time.",
  "I regret my interest in motorcycles. All I got was an amputated leg and this t-shirt.",
  "I regret playing high school football. Cornerback. Too many concussions for little gain.",
  "Not playing football or another team sport..",
  "I regret boxing. I probably have CTE honestly",
  "I got a personal invitation to work for Facebook in 2007. I didn't take it seriously enough but I would have been in a really good position in life by now.",
  "As much as it hurts to say: having an autistic son",
  "The only thing I truly regret is drinking too much alcohol for thirteen years. Waiting to find out if it kills me like it did my grandfather makes me feel sad.",
  "My biggest regret was not getting into therapy sooner. I knew that I self medicated my issues with behavior and addictions, but was too immature to face them. Now that I have, my life has such a higher quality. It's not longer what I do in my life, but the quality of each day and my interactions with others.",
  "Seriously, never go after the money. It's not worth it, fuck I hate my job.",
  "Spending most of my life obsessing over my weight. Seriously there are so many things that I either never did because I was \"too fat\" or put off until I could lose x number of pounds. Dieting instead of living my life. Secondly but related, staying in bad relationships because fat me couldn't possibly get another man.",
  "Not moving out of my small town of 6,000 people. I got comfortable and put down roots here. Really wish I would have moved somewhere with more opportunities. I was going to join the Coast Guard at the same time as a buddy of mine but I backed out because of a girl (who ended up dumping me a year later) and he joined anyway. He lives all the way across the country in Washington. He's retired at 40 and works part time.",
  "I wish in high school I would have been more sociable. I wasn't necessarily shy, but always felt like I didn't fit in with everyone else in school except for my one best friend (I went to a small all girls school), and that one friend and I have drifted apart unfortunately.",
  "spent most of my thirties paying off the credit card debt and working off the piles of fast food and soda from my 20s while wondering how life would have been different if I'd hadn't buried myself in computer games and avoided human contact for so long",
  "Having wasted ten years on Reddit.",
  "Going on vacation and leaving my recently sober twin brother at my house alone. I knew something was wrong when he wouldn't answer the phone. Found him face down in my living room. It's been 9 months and I still can't close my eyes without seeing my best friend alone on the ground. His phone was 2 foot away and he couldn't answer it because he was already gone.",
  "Few years back I started to date my best friend. A couple months in it was clear it wasn't going to work out, I was moody and emotional back then, and she had some personal issues. But instead of handling it like and adult, I blew up at her and ruined not just the relationship, but also one of the best friendships I've ever had. Hurts every time I think about it.",
  "Assaulting my father when I was eighteen and ending up in prison",
  "Not spending enough time by myself - single, not in a relationship. There's so many things I want to do that I can't really do if I'm with a partner.",
  "Choosing to study Journalism and specialized in news paper reporting. It was the beginning of the 90's and I didn't realize how computers would change the business",
  "Wasting so much of my late teens/early twenties getting stoned and playing video games.",
  "Letting myself get so fat. I was never really taught proper nutrition, nor was it enforced as a child. Now I'm an adult with very low self control when it comes to eating, and that lack of discipline spills over into other aspects of my life.",
  "Picking up smoking cigarettes. It's the one thing I just can't go without. Sense of smell is pretty much gone. Taste isn't as strong as it was. And it's pretty expensive. I smoke Newports which are on average $6.50 a pack. Pack a day that's close to $200 a month. For what? Decreased senses. Increased chances of serious health problems. Smoking is a bitch",
  "Not sending my dog to the vet on Saturday. He was really sick, but my family and I figured he would recover if we gave him meds and helped him out, because it worked before. If he didn't get better, we'd take him to the vet on Monday. I found his lifeless body Sunday at 7 AM.",
  "Eating a marshmallow while high on acid. Worst decision of my life.",
  "The fact that I've never put myself in a place were I could really thrive, and just blame it on the world being unfair.",
  "Never living in the moment. There is a tendency for people to be so focused on what possibilities the future holds that they lose sight of the opportunities right in front of them. I am in my third year of college now and I have numerous regrets for not being proactive to create lasting friendships and memories because I was and still am focused on my education and GPA.",
  "Not taking better care of my body when I was younger. I thought I was invincible and put my body through hell working out and probably not with good form. Now I have discs that'll forever bother me in my spine because of it. I miss the days of being pain free and all it would have taken was discipline and not thinking I was a superhero nor that my body wouldn't catch up to me eventually.",
  "Having an affair with a married man. I'm a good person, except that. I was young and a fucking idiot.",
  "Sleeping with a drunk persistent friend, I didn't want to, just because he wouldn't leave me alone while staying at my house. I had a big day at work the next day and thought the only way I'd ever get to sleep was if I just fucked him so he'd pass out and leave me alone. Condom broke. Things did not end well for me.",
  "I finished college and gave up my dream career to move home and take care of my ailing father. It cost me my future, and now I'm stuck in a bullshit factory job because I can't find anything better. It pays the bills and feeds my kid, that's all that matters. I spent thousands of dollars I didn't have, and three years of my life to escape the auto industry and here I am. At a slightly better auto parts factory job.",
  "I fucked up the best relationship I'll ever have. She loved me to death and would do anything for me. But for some reason I wasn't happy, I broke up with her and half a year later I realized what I had and what I messed up. But she was happy with another man and I was left heartbroken. If I could go back and change it I so would.",
  "Hurting my husband (then boyfriend) at the beginning of our relationship. I didn't know what or who I wanted and just messed around way too much but he never gave up on me. I face every day knowing that nothing he could ever do to me would ever pay me back for everything I've put him through.",
  "I wish I would have stopped and saw my grandmother more. I don't have many regrets but this is the biggest. I used to pass by her house to my friends and girlfriends all the time and never stopped in. Either I was going to party or get laid and that was way morre important than stopping to see if she needed anything, or just to say hi. She was in her middle 80's and loved her grandkids. Even for 5 minutes or to have a cup of tea or play a hand of rummy with her, dammit, now I pissed at myself again. What a wonderful, hardworking woman. I tell my kids about this regret and to please just stop and say hi to their grandparents.",
  "All the sexual things I did with men I wasn't in a relationship with. They disappeared after they got what they wanted. I was young and inexperienced but it is still my biggest regret.",
  "I haven't mustered the strength to end it",
  "Spending too much time and energy on a relationship I knew was doomed to fail and then spending too much time and energy on mourning the failure of said relationship.",
  "I was going to become a cardiologist but I wanted to travel the world and have kids and didn’t want endure such a long training period. Now I’m in my 30s and no kids, no cardiologist salary, but I have travelled the world. Guess 1 out of 3 isn’t too bad!",
  "The biggest regret I have from my twenties is that I didn't develop any long lasting friendships in college. I had a lot of friends, and a ton of acquaintances, but there's not a single [person I know from my twenties that I still speak with and I really wish there were.",
  "I wasted an entire year of my life living in my parent's basement, working a shitty job, being an alcoholic and pretty much not talking to anyone socially. One day I woke up, packed up my car and moved halfway across the country to crash with a friend in a new city. Pretty much saved my life.",
  "Focusing too much on my career and not enough on friends and relationships. I have a great career and the financial stability to go places and do things, but no one to do them with because I was a workaholic and ignored my social life",
  "Dropping out of college when I did. I was on track in the early/mid 2000s to graduate with a degree in education (and was working briefly as a sub/classroom assistant at a middle school), but for some foolish reason I dropped out. I did eventually go back, but by then I graduated in 2010 after the economy crashed and all the school districts started laying off. I never did get a full time teaching position after that.",
  "I had a child in my 20s which I don't regret, but I do wish I traveled more before having said child.",
  "Not traveling to places while I can. Married with a kid now and travelling isnt really an option nowadays.",
  "I'm actually pretty satisfied with how my twenties played out. My biggest regret is staying in a job I hated for too long.",
  "Not going into therapy sooner.",
  "I wish I'd moved further away, and travelled more. I also wish I'd recognized that I had super fucking toxic friends and that I needed to drink less booze and hang out with better people.",
  "I wasted too much time looking back. Don't look back, keep moving forwards",
  "Not living abroad. I have a great career and life now. But I can't help but feel like the opportunity for me to live in a different country has passed.",
  "Not pursing a career because I was hoping to have children. I'm in my mid 30s now, with no kids and no degree.",
  "I regret that I didn't save more money for my retirement.",
  "not taking more chances on everything but instead holding back and playing everything safe, especially with career and relationships.",
  "Spent too much fucking time playing video games instead of interacting with my wife. Almost got divorced ever the original Everquest.",
  "I regret all the time I spent at work in a field I hate. I'm still doing it and it has ruined my life. Few friends, fewer lovers and since the bubble I've even had to give up/cut back on a lot of the 'stuff' I acquired/enjoyed that was supposed to offset the soul sucking nature of my career.",
  "I should have had more hookups and enjoyed being young and carefree. Instead I was on work travel, sleeping alone in endless hotels.",
  "Graduate school. Complete waste of time and money.",
  "I regret any computer job I had. for me, the PC/software job was a soul sucking experience. I wish I did something more physical and gratifying.",
  "I know it's not as major as some of the other things here, but I think I'm studying the wrong thing in life. I let myself get bullied by family into going to university for the sciences, when really I want to do the arts. I've almost got my degree and I seem to regret it more every day",
  "Failing out of college. Didn’t even know what I wanted to do, but at least I could have just waited. Instead, I went and ruined it. Now I’m 25 and feel like I’m going to be stuck doing shit, low paying jobs the rest of my life. My little debt I did accrue from college is almost paid off, but how the hell can i go back now? I can’t work full time and go to classes for 4 years.",
  "I ruined things beyond repair with a woman I love. I had so many chances to really show her how I felt and I fucked them all up. She doesn't want to be close to me at all anymore, and I can't stop thinking about her. I have to struggle to keep it together at work, I cry every night, I constantly think about how she used to smile at me, the way her eyes shone when she was looking up at me, the feeling of her lips on mine. I lost all of that and will never have it again, and it feels like a physical weight I can't escape.",
  "Drinking and smoking weed from 14 to 27. Other people do this and are just kind of slackers, but it exacerbated latent mental health issues that went undiagnosed and untreated for years. Now I’m almost 30, a year sober and realizing How could have been a good person and successful if I hadn’t self medicated all those years, but instead I’m trying to start my life for the first time and feeling like I’m too old and screwed up to carve out a piece of comfort and safety."
];
